FROM python:3.11-slim

RUN apt-get update \
    && apt-get install --yes --no-install-recommends curl \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    boto3==1.35.90 \
    mlflow==2.18.0 \
    psycopg2-binary==2.9.10 \
    sqlalchemy==2.0.36 \
    virtualenv==20.28.1

WORKDIR /app

