FROM apache/airflow:2.10.5-python3.11

RUN pip install --no-cache-dir \
    apache-airflow-providers-amazon==9.4.0 \
    apache-airflow-providers-postgres==5.14.0 \
    boto3==1.35.90 \
    mlflow-skinny==2.18.0

